# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mayhem

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_07478136f66c4f5b9d310e9c43b8c8af }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1f29bd3c16174cd78d710ded9605e4cd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_07478136f66c4f5b9d310e9c43b8c8af }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mayhem'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_73d72833e4a6493786831bb1a4eebb98 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_07478136f66c4f5b9d310e9c43b8c8af }}/appsvc/staticsite:${{ github.sha }}'